### ISSUE TITLE
/check throws error for unknown reason

### ISSUE THREAD

**Issue by Dico200** [RedstonerServer/redstoner-utils#20]
Since commit 181c6cc and 62569c7, /check throws an error on the server:

```
[14:43:56 INFO]: + Curs3d
[14:43:57 INFO]:  Arhur → ?
[14:43:58 INFO]: octopuscraft issued server command: /w peterjiangTW cheaper
>check penis
[14:44:07 INFO]:
--=[ Check ]=--
[14:44:07 INFO]: Please notice that the data may not be fully accurate!
[14:44:07 INFO]:
[14:44:07 INFO]:    -- Data provided by Redstoner
[14:44:07 INFO]: >  UUID: 4d182744-387f-3826-afc7-efa86783a141
[14:44:07 INFO]: >  First joined: (y-m-d h:m:s) 1970-01-01 01:00
[14:44:07 INFO]: >  Last seen: (y-m-d h:m:s) 1970-01-01 01:00
[14:44:07 INFO]: >  Website account: None
[14:44:07 INFO]: >    email: None
[14:44:07 INFO]:    -- Data provided by ipinfo.io
[14:44:07 INFO]: >  Country: None
[14:44:07 INFO]: >  Network: None
[14:44:07 INFO]:    -- Data provided by Mojang
[14:44:08 WARN]: [RedstonerUtils] Traceback (most recent call last):
  File "/etc/minecraft/redstoner/plugins/redstoner-utils.py.dir/check.py", line 70, in get_all_data
    msg(sender, "&6>  All ingame names used so far: &e%s" % get_all_names(player))
  File "/etc/minecraft/redstoner/plugins/redstoner-utils.py.dir/check.py", line 47, in get_all_names
    names = json.load(urllib2.urlopen("https://api.mojang.com/user/profiles/%s/names" % uuid))
  File "/etc/minecraft/redstoner/plugins/pypluginloader.jar/Lib/json/__init__.py", line 286, in load
    return loads(fp.read(),
  File "/etc/minecraft/redstoner/plugins/pypluginloader.jar/Lib/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/etc/minecraft/redstoner/plugins/pypluginloader.jar/Lib/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/etc/minecraft/redstoner/plugins/pypluginloader.jar/Lib/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

[14:44:08 INFO]: Sorry, something went wrong while fetching data
```
I don't get this error locally on my server, I get an error telling me it can't connect to MySQL - which makes perfect sense - but something is at least broken here. I don't know exactly what it is.

**Comment by jomo** [comment]
I think we aren't catching HTTP errors from Mojang servers
