### ISSUE TITLE
/pluginversions fails

### ISSUE THREAD

**Issue by jomo** [RedstonerServer/redstoner-utils#3]
``` Java
[17:23:25] [MainThread/INFO]: --=[ Plugin versions ]=--
[17:23:25] [MainThread/WARN]: Unexpected exception while parsing console command "pluginversions"
org.bukkit.command.CommandException: Unhandled exception executing command 'pluginversions' in plugin RedstonerUtils v3.0.0
  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643) ~[spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:629) [spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]
Caused by: org.python.core.PyException
  at org.python.core.Py.JavaError(Py.java:516) ~[?:?]
  at org.python.core.PyTableCode.call(PyTableCode.java:168) ~[?:?]
  at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[?:?]
  at org.python.core.PyFunction.function___call__(PyFunction.java:406) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:401) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:391) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:386) ~[?:?]
  at net.lahwran.bukkit.jython.PythonCommandHandler.call(PythonCommandHandler.java:57) ~[?:?]
  at net.lahwran.bukkit.jython.PythonCommandHandler.onCommand(PythonCommandHandler.java:100) ~[?:?]
  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-9a88a38-e2c4f20]
  ... 8 more
Caused by: java.lang.NoClassDefFoundError: Lcom/zachsthings/netevents/NetEventsPlugin;
  at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_40-internal]
  at java.lang.Class.privateGetDeclaredFields(Class.java:2570) ~[?:1.8.0_40-internal]
  at java.lang.Class.getDeclaredFields(Class.java:1903) ~[?:1.8.0_40-internal]
  at org.python.core.PyJavaType.init(PyJavaType.java:404) ~[?:?]
  at org.python.core.PyType.createType(PyType.java:1356) ~[?:?]
  at org.python.core.PyType.addFromClass(PyType.java:1293) ~[?:?]
  at org.python.core.PyType.fromClass(PyType.java:1383) ~[?:?]
  at org.python.core.PyJavaType.wrapJavaObject(PyJavaType.java:85) ~[?:?]
  at org.python.core.adapter.ClassicPyObjectAdapter.adapt(ClassicPyObjectAdapter.java:124) ~[?:?]
  at org.python.core.Py.java2py(Py.java:1669) ~[?:?]
  at org.python.core.PyArray.pyget(PyArray.java:1246) ~[?:?]
  at org.python.core.PySequence$DefaultIndexDelegate.getItem(PySequence.java:520) ~[?:?]
  at org.python.core.SequenceIndexDelegate.checkIdxAndFindItem(SequenceIndexDelegate.java:88) ~[?:?]
  at org.python.core.PySequence.seq___finditem__(PySequence.java:346) ~[?:?]
  at org.python.core.PySequence.__finditem__(PySequence.java:342) ~[?:?]
  at org.python.core.PySequenceIter.__iternext__(PySequenceIter.java:24) ~[?:?]
  at org.python.core.WrappedIterIterator.hasNext(WrappedIterIterator.java:23) ~[?:?]
  at org.python.core.PyList.list___init__(PyList.java:112) ~[?:?]
  at org.python.core.PyList$exposed___new__.createOfType(Unknown Source) ~[?:?]
  at org.python.core.PyOverridableNew.new_impl(PyOverridableNew.java:12) ~[?:?]
  at org.python.core.PyType.invokeNew(PyType.java:480) ~[?:?]
  at org.python.core.PyType.type___call__(PyType.java:1650) ~[?:?]
  at org.python.core.PyType.__call__(PyType.java:1640) ~[?:?]
  at org.python.core.PyObject.__call__(PyObject.java:403) ~[?:?]
  at org.python.core.PyObject.__call__(PyObject.java:407) ~[?:?]
  at misc$py.on_pluginversions_command$4(plugins/redstoner-utils.py.dir/misc.py:108) ~[?:?]
  at misc$py.call_function(plugins/redstoner-utils.py.dir/misc.py) ~[?:?]
  at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[?:?]
  at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[?:?]
  at org.python.core.PyFunction.function___call__(PyFunction.java:406) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:401) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:391) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:386) ~[?:?]
  at net.lahwran.bukkit.jython.PythonCommandHandler.call(PythonCommandHandler.java:57) ~[?:?]
  at net.lahwran.bukkit.jython.PythonCommandHandler.onCommand(PythonCommandHandler.java:100) ~[?:?]
  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-9a88a38-e2c4f20]
  ... 8 more
Caused by: java.lang.ClassNotFoundException: com.zachsthings.netevents.NetEventsPlugin
  at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_40-internal]
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_40-internal]
  at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_40-internal]
  at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_40-internal]
  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-9a88a38-e2c4f20]
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_40-internal]
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_40-internal]
  at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_40-internal]
  at java.lang.Class.privateGetDeclaredFields(Class.java:2570) ~[?:1.8.0_40-internal]
  at java.lang.Class.getDeclaredFields(Class.java:1903) ~[?:1.8.0_40-internal]
  at org.python.core.PyJavaType.init(PyJavaType.java:404) ~[?:?]
  at org.python.core.PyType.createType(PyType.java:1356) ~[?:?]
  at org.python.core.PyType.addFromClass(PyType.java:1293) ~[?:?]
  at org.python.core.PyType.fromClass(PyType.java:1383) ~[?:?]
  at org.python.core.PyJavaType.wrapJavaObject(PyJavaType.java:85) ~[?:?]
  at org.python.core.adapter.ClassicPyObjectAdapter.adapt(ClassicPyObjectAdapter.java:124) ~[?:?]
  at org.python.core.Py.java2py(Py.java:1669) ~[?:?]
  at org.python.core.PyArray.pyget(PyArray.java:1246) ~[?:?]
  at org.python.core.PySequence$DefaultIndexDelegate.getItem(PySequence.java:520) ~[?:?]
  at org.python.core.SequenceIndexDelegate.checkIdxAndFindItem(SequenceIndexDelegate.java:88) ~[?:?]
  at org.python.core.PySequence.seq___finditem__(PySequence.java:346) ~[?:?]
  at org.python.core.PySequence.__finditem__(PySequence.java:342) ~[?:?]
  at org.python.core.PySequenceIter.__iternext__(PySequenceIter.java:24) ~[?:?]
  at org.python.core.WrappedIterIterator.hasNext(WrappedIterIterator.java:23) ~[?:?]
  at org.python.core.PyList.list___init__(PyList.java:112) ~[?:?]
  at org.python.core.PyList$exposed___new__.createOfType(Unknown Source) ~[?:?]
  at org.python.core.PyOverridableNew.new_impl(PyOverridableNew.java:12) ~[?:?]
  at org.python.core.PyType.invokeNew(PyType.java:480) ~[?:?]
  at org.python.core.PyType.type___call__(PyType.java:1650) ~[?:?]
  at org.python.core.PyType.__call__(PyType.java:1640) ~[?:?]
  at org.python.core.PyObject.__call__(PyObject.java:403) ~[?:?]
  at org.python.core.PyObject.__call__(PyObject.java:407) ~[?:?]
  at misc$py.on_pluginversions_command$4(plugins/redstoner-utils.py.dir/misc.py:108) ~[?:?]
  at misc$py.call_function(plugins/redstoner-utils.py.dir/misc.py) ~[?:?]
  at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[?:?]
  at org.python.core.PyBaseCode.call(PyBaseCode.java:301) ~[?:?]
  at org.python.core.PyFunction.function___call__(PyFunction.java:406) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:401) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:391) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:386) ~[?:?]
  at net.lahwran.bukkit.jython.PythonCommandHandler.call(PythonCommandHandler.java:57) ~[?:?]
  at net.lahwran.bukkit.jython.PythonCommandHandler.onCommand(PythonCommandHandler.java:100) ~[?:?]
  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-9a88a38-e2c4f20]
  ... 8 more
```
- `com.zachsthings.netevents.NetEventsPlugin` is [imported by PermissionsEx](https://github.com/PEXPlugins/PermissionsEx/blob/6e361c364c6525815f2b7383a1e7cfc5e7ab6fdb/src/main/java/ru/tehkode/permissions/bukkit/PermissionsEx.java#L28) (maybe PEX just the first plugin in the list, and NetEvents is unrelated)
- Apparently it's breaking [somewhere here](https://github.com/RedstonerServer/redstoner-utils/blob/363f5cdddab1c1b16a7fa82adcb8092d069f8e47/misc.py#L107)

**Comment by jomo** [comment]
I was pretty sure you'd also get the error when you only run `server.getPluginManager().getPlugins()` - might be a bug in jython though.
