### ISSUE TITLE
Cycle error

### ISSUE THREAD

**Issue by jomo** [RedstonerServer/redstoner-utils#6]
```Log
[Server thread/ERROR]: Could not pass event PlayerItemHeldEvent to RedstonerUtils v3.0.0
org.python.core.PyException
  at org.python.core.Py.JavaError(Py.java:516) ~[?:?]
  at org.python.core.PyTableCode.call(PyTableCode.java:168) ~[?:?]
  at org.python.core.PyBaseCode.call(PyBaseCode.java:149) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:357) ~[?:?]
  at cycle$py.on_slot_change$2(plugins/redstoner-utils.py.dir/cycle.py:47) ~[?:?]
  at cycle$py.call_function(plugins/redstoner-utils.py.dir/cycle.py) ~[?:?]
  at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[?:?]
  at org.python.core.PyBaseCode.call(PyBaseCode.java:134) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:347) ~[?:?]
  at org.python.core.PyFunction.__call__(PyFunction.java:342) ~[?:?]
  at net.lahwran.bukkit.jython.PythonListener.fireEvent(PythonListener.java:43) ~[?:?]
  at net.lahwran.bukkit.jython.PythonPluginLoader$1.execute(PythonPluginLoader.java:420) ~[?:?]
  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5ffe41c-c806831]
  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:884) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at net.minecraft.server.v1_8_R1.PacketPlayInHeldItemSlot.a(SourceFile:30) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at net.minecraft.server.v1_8_R1.PacketPlayInHeldItemSlot.a(SourceFile:8) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40-internal]
  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40-internal]
  at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-5ffe41c-c806831]
  at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]
Caused by: java.lang.NullPointerException
  at net.minecraft.server.v1_8_R1.ChatModifier.hashCode(SourceFile:205) ~[spigot.jar:git-Spigot-5ffe41c-c806831]
  at net.minecraft.server.v1_8_R1.ChatBaseComponent.hashCode(SourceFile:117) ~[spigot.jar:git-Spigot-5ffe41c-c806831]
  at java.util.AbstractList.hashCode(AbstractList.java:541) ~[?:1.8.0_40-internal]
  at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftMetaBook.applyHash(CraftMetaBook.java:285) ~[spigot.jar:git-Spigot-5ffe41c-c806831]
  at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftMetaBookSigned.applyHash(CraftMetaBookSigned.java:117) ~[spigot.jar:git-Spigot-5ffe41c-c806831]
  at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftMetaItem.hashCode(CraftMetaItem.java:736) ~[spigot.jar:git-Spigot-5ffe41c-c806831]
  at org.bukkit.inventory.ItemStack.hashCode(ItemStack.java:368) ~[spigot.jar:git-Spigot-5ffe41c-c806831]
  at org.python.core.PyJavaType$6.__call__(PyJavaType.java:600) ~[?:?]
  at org.python.core.PyObjectDerived.hashCode(PyObjectDerived.java:759) ~[?:?]
  at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1012) ~[?:1.8.0_40-internal]
  at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_40-internal]
  at java.util.Collections$SetFromMap.add(Collections.java:5461) ~[?:1.8.0_40-internal]
  at org.python.core.BaseSet._update(BaseSet.java:43) ~[?:?]
  at org.python.core.BaseSet._update(BaseSet.java:24) ~[?:?]
  at org.python.core.PySet.set___init__(PySet.java:44) ~[?:?]
  at org.python.core.PySet$exposed___new__.createOfType(Unknown Source) ~[?:?]
  at org.python.core.PyOverridableNew.new_impl(PyOverridableNew.java:12) ~[?:?]
  at org.python.core.PyType.invokeNew(PyType.java:480) ~[?:?]
  at org.python.core.PyType.type___call__(PyType.java:1650) ~[?:?]
  at org.python.core.PyType.__call__(PyType.java:1640) ~[?:?]
  at org.python.core.PyObject.__call__(PyObject.java:403) ~[?:?]
  at org.python.core.PyObject.__call__(PyObject.java:407) ~[?:?]
  at cycle$py.do_cycle$3(plugins/redstoner-utils.py.dir/cycle.py:67) ~[?:?]
  at cycle$py.call_function(plugins/redstoner-utils.py.dir/cycle.py) ~[?:?]
  at org.python.core.PyTableCode.call(PyTableCode.java:165) ~[?:?]
  ... 24 more
```

**Comment by jomo** [comment]
Actually was a bug in spigot

**Comment by jomo** [comment]
Only happens with signed books in the inventory, Mojang bug according to Thinkofdeath.

**Comment by jomo** [comment]
[Fix null pointer in ChatBaseComponent's hashCode method](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/CraftBukkit/commits/1a84bacbdd6)

That should fix it, will test.
